#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hyperstart
Version  : 9e31bd560357c358ae4bbd94e86066847996620a
Release  : 28
URL      : https://github.com/clearcontainers/hyperstart/archive/0.7.0-clearcontainers/9e31bd560357c358ae4bbd94e86066847996620a.tar.gz
Source0  : https://github.com/clearcontainers/hyperstart/archive/0.7.0-clearcontainers/9e31bd560357c358ae4bbd94e86066847996620a.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: hyperstart-bin
Requires: hyperstart-config
BuildRequires : pkgconfig(systemd)

%description
The init Task for HyperContainer. You can get the binary installer of
HyperContainer and HyperStart through https://github.com/hyperhq/hyperd.

%package bin
Summary: bin components for the hyperstart package.
Group: Binaries
Requires: hyperstart-config

%description bin
bin components for the hyperstart package.


%package config
Summary: config components for the hyperstart package.
Group: Default

%description config
config components for the hyperstart package.


%prep
%setup -q -n hyperstart-0.7.0-clearcontainers

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1512428245
%autogen --disable-static --enable-daemon
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1512428245
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hyperstart

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/hyperstart.service
